Allow multiple packages at a time

diff --git a/bin/link-package b/bin/link-package
--- a/bin/link-package
+++ b/bin/link-package
@@ -3,23 +3,37 @@
 set -euo pipefail
 
 if [ $# -eq 0 ]; then
-    echo "You must provide an argument for the package you wish to link"
+    echo "You must provide arguments for the packages you wish to link e.g. 'link-package platform frontend ui-components'"
     exit 1
 fi
 
-PACKAGE=${1}
 MONOREPO_ROOT=${LINK_PACKAGE_ROOT:-~/workspace/frontend-platform}
-DIST_FOLDER=${MONOREPO_ROOT}/packages/${PACKAGE}/build
-BUILD_COMMAND=${LINK_PACKAGE_COMMAND:-"yarn build"}
+BUILD_COMMAND=${LINK_PACKAGE_COMMAND:-"yarn build-quick"}
+TARBALL_LIST=''
 
-if [ -f "${MONOREPO_ROOT}/packages/${PACKAGE}/package.json" ]; then
-    echo "package.json found for ${PACKAGE}"
-else
-    echo "package.json not found in ${MONOREPO_ROOT}/packages/${PACKAGE}!"
-    exit 1
-fi
+create_tarballs() {
+    local PACKAGE=${1}
+    local BUILD_FOLDER=${MONOREPO_ROOT}/packages/${PACKAGE}/build
 
-(cd ${MONOREPO_ROOT} && ${BUILD_COMMAND} && cd ${DIST_FOLDER} && npm pack)
-TARBALL=$(ls ${DIST_FOLDER}/*.tgz)
-echo "Installing ${TARBALL}"
-npm i ${TARBALL}
+    if [ -f "${MONOREPO_ROOT}/packages/${PACKAGE}/package.json" ]; then
+        echo "Found package.json for ${PACKAGE}"
+    else
+        echo "Can't find package.json in ${MONOREPO_ROOT}/packages/${PACKAGE}!"
+        exit 1
+    fi
+
+    echo "Packing ${PACKAGE}"
+    (cd ${BUILD_FOLDER} && npm pack)
+
+    local TARBALL=$(ls ${BUILD_FOLDER}/*.tgz)
+    TARBALL_LIST="${TARBALL_LIST} ${TARBALL}"
+}
+
+echo "Building monorepo"
+(cd ${MONOREPO_ROOT} && ${BUILD_COMMAND})
+
+echo "Pack all packages"
+for PACKAGE in "$@"; do create_tarballs "${PACKAGE}"; done
+
+echo "Installing tarballs"
+npm i ${TARBALL_LIST}
